BEGIN;

-- Permite que el backend cree PIN_ID sin generar IDs manualmente.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name = 'pin'
      AND column_name = 'pin_id'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE pin ALTER COLUMN pin_id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('pin', 'pin_id'),
  COALESCE(MAX(pin_id), 0) + 1,
  false
)
FROM pin;

COMMIT;
